### 
@baseUrl = http://localhost:8000
@token = {{login.response.body.data}}

### 회원가입 API
POST {{baseUrl}}/api/v1/signup/local
content-type: application/json

{
  "email":"test@test.com",
  "name": "테스트용",
  "password":"!test1234"
}

### 로그인 API
# @name login
POST {{baseUrl}}/api/v1/auth/local
content-type: application/json

{
  "email":"test@test.com",
  "password":"!test1234"
}

### 멤버 정보를 불러오는 API
GET {{baseUrl}}/api/v1/member
Authorization: Bearer {{token}}

{
  "email":"test@test.com",
  "password":"!test1234"
}

### 멤버 정보를 수정하는 API
PUT {{baseUrl}}/api/v1/member
content-type: application/json
Authorization: Bearer {{token}}

{
  "name":"변경 후",
  "profileUrl":"http://profile.com"
}


### 게시물을 등록하는 API
POST {{baseUrl}}/api/v1/product
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "새로운 게시물",
  "price": 10000,
  "profileUrl": "http://profile.com",
  "content": "게시물의 상세 내용 설명"
}

### 모든 중고 거래 물건을 조회하는 API
GET {{baseUrl}}/api/v1/product/list?limit=10&offset=0


### 모든 중고 거래 물건을 조회하는 API (검색)
GET {{baseUrl}}/api/v1/product/list?limit=10&offset=0&keyword=

### 좋아요 추가 & 취소 토글

PUT {{baseUrl}}/api/v1/product/like
content-type: application/json
Authorization: Bearer {{token}}

{
 "productId": 12
}